import os
import json
import argparse
from collections import defaultdict


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Filter predicted boxes with confidence thresholding and class-wise NMS, "
            "then merge the retained pseudo labels with the original few-shot annotations."
        )
    )
    parser.add_argument(
        "--gt_json",
        type=str,
        required=True,
        help="Path to the original few-shot annotation JSON.",
    )
    parser.add_argument(
        "--pred_json",
        type=str,
        required=True,
        help="Path to the prediction JSON generated by the detector.",
    )
    parser.add_argument(
        "--all_train_json",
        type=str,
        required=True,
        help="Path to the COCO-style image JSON generated for pseudo labeling.",
    )
    parser.add_argument(
        "--output_json",
        type=str,
        required=True,
        help="Path to save the merged pseudo-label annotation JSON.",
    )
    parser.add_argument(
        "--score_threshold",
        type=float,
        default=0.5,
        help="Confidence threshold for filtering predictions. Default: 0.5",
    )
    parser.add_argument(
        "--nms_iou_threshold",
        type=float,
        default=0.5,
        help="IoU threshold for class-wise NMS. Default: 0.5",
    )
    return parser.parse_args()


def xywh_to_xyxy(box):
    x, y, w, h = box
    return [x, y, x + w, y + h]


def compute_iou(box1, box2):
    x1_1, y1_1, x2_1, y2_1 = xywh_to_xyxy(box1)
    x1_2, y1_2, x2_2, y2_2 = xywh_to_xyxy(box2)

    inter_x1 = max(x1_1, x1_2)
    inter_y1 = max(y1_1, y1_2)
    inter_x2 = min(x2_1, x2_2)
    inter_y2 = min(y2_1, y2_2)

    inter_w = max(0.0, inter_x2 - inter_x1)
    inter_h = max(0.0, inter_y2 - inter_y1)
    inter_area = inter_w * inter_h

    area1 = max(0.0, x2_1 - x1_1) * max(0.0, y2_1 - y1_1)
    area2 = max(0.0, x2_2 - x1_2) * max(0.0, y2_2 - y1_2)

    union = area1 + area2 - inter_area
    if union <= 0:
        return 0.0
    return inter_area / union


def nms_per_class(preds, iou_thr=0.5):
    """
    Perform class-wise NMS for predictions grouped by (image_id, category_id).

    Args:
        preds: list of dicts, each containing:
               image_id, category_id, bbox, score
        iou_thr: IoU threshold for NMS

    Returns:
        List of predictions after NMS.
    """
    grouped = defaultdict(list)
    for p in preds:
        key = (p["image_id"], p["category_id"])
        grouped[key].append(p)

    kept = []
    for _, items in grouped.items():
        items = sorted(items, key=lambda x: x["score"], reverse=True)
        selected = []

        for cur in items:
            keep_flag = True
            for s in selected:
                if compute_iou(cur["bbox"], s["bbox"]) > iou_thr:
                    keep_flag = False
                    break
            if keep_flag:
                selected.append(cur)

        kept.extend(selected)

    return kept


def main():
    args = parse_args()

    # =========================
    # Load files
    # =========================
    with open(args.gt_json, "r", encoding="utf-8") as f:
        gt_data = json.load(f)

    with open(args.pred_json, "r", encoding="utf-8") as f:
        pred_data = json.load(f)

    with open(args.all_train_json, "r", encoding="utf-8") as f:
        all_train_data = json.load(f)

    # =========================
    # Original few-shot image ids (used for statistics only)
    # =========================
    gt_image_ids = set(img["id"] for img in gt_data["images"])

    # =========================
    # Step 1: score threshold filtering
    # =========================
    filtered_preds = []
    for p in pred_data:
        if p.get("score", 0.0) < args.score_threshold:
            continue
        filtered_preds.append(p)

    print(f"[Info] Number of predictions after score filtering: {len(filtered_preds)}")

    # =========================
    # Step 2: class-wise NMS
    # =========================
    filtered_preds = nms_per_class(filtered_preds, iou_thr=args.nms_iou_threshold)
    print(f"[Info] Number of predictions after NMS: {len(filtered_preds)}")

    # =========================
    # Build image_id -> image_info map
    # =========================
    all_image_map = {img["id"]: img for img in all_train_data["images"]}
    pseudo_image_ids = set(p["image_id"] for p in filtered_preds)

    # =========================
    # Build pseudo annotations
    # =========================
    existing_ann_ids = [ann["id"] for ann in gt_data["annotations"]] if gt_data["annotations"] else [0]
    next_ann_id = max(existing_ann_ids) + 1

    pseudo_annotations = []
    for p in filtered_preds:
        x, y, w, h = p["bbox"]
        ann = {
            "id": next_ann_id,
            "image_id": p["image_id"],
            "category_id": p["category_id"],
            "area": float(w * h),
            "bbox": [float(x), float(y), float(w), float(h)],
            "iscrowd": 0,
            "attributes": {
                "occluded": False
            },
        }
        pseudo_annotations.append(ann)
        next_ann_id += 1

    # =========================
    # Merge images
    # - Keep original few-shot images
    # - Add new images involved in pseudo labels
    # =========================
    merged_images = list(gt_data["images"])
    existing_image_ids = set(img["id"] for img in merged_images)

    for image_id in pseudo_image_ids:
        if image_id not in existing_image_ids:
            if image_id not in all_image_map:
                print(f"[Warning] image_id={image_id} not found in all_train_json, skipped.")
                continue
            merged_images.append(all_image_map[image_id])

    # =========================
    # Merge annotations
    # =========================
    merged_annotations = list(gt_data["annotations"]) + pseudo_annotations

    # =========================
    # Save final COCO-style JSON
    # =========================
    merged_data = {
        "images": merged_images,
        "annotations": merged_annotations,
        "categories": gt_data["categories"],
    }

    os.makedirs(os.path.dirname(args.output_json), exist_ok=True)
    with open(args.output_json, "w", encoding="utf-8") as f:
        json.dump(merged_data, f, ensure_ascii=False, indent=4)

    # =========================
    # Statistics
    # =========================
    num_new_images = len([i for i in merged_images if i["id"] not in gt_image_ids])

    print(f"[Done] Saved to: {args.output_json}")
    print(f"[Info] Original few-shot images: {len(gt_data['images'])}")
    print(f"[Info] Newly added pseudo-labeled images: {num_new_images}")
    print(f"[Info] Original ground-truth annotations: {len(gt_data['annotations'])}")
    print(f"[Info] Added pseudo annotations: {len(pseudo_annotations)}")
    print(f"[Info] Final number of images: {len(merged_images)}")
    print(f"[Info] Final number of annotations: {len(merged_annotations)}")


if __name__ == "__main__":
    main()